# Generated by Django 6.1 on 2026-09-01 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoTranscriptData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=255, unique=True)),
                ('video_name', models.CharField(max_length=255)),
                ('video_duration', models.IntegerField()),
                ('video_count', models.IntegerField()),
                ('channel_name', models.CharField(max_length=50)),
                ('transcript', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
